<?php

/**
 * @file
 * Contains version_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function version_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the version_test module.
    case 'help.page.version_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test module and composer versions. Version 1.0.4.') . '</p>';
      return $output;

    default:
  }
}
